from ehk_model_old.stats.in_degree import InDegreeCollector
from ehk_model_old.stats.echo_chamber import TriadsCountCollector, ClusteringCollector, SegregationIndexCollector
from ehk_model_old.stats.distance import DistanceCollectorDiscrete
from ehk_model_old.stats.network import NetworkLayoutCollector